

# --SITE SETTINGS--
title: Earthseeding Altadena
email: Phumisit Jaab Veskijkul veskijku@usc.edu or Alison Hirsch alisonh@usc.edu 
description: This project features the community mapping efforts of Landscape Justice Initiative for Altadena
baseurl: "/EarthseedAltadena" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_repo: https://github.com/veskijku/EarthseedAltadena
copyright_statement: Original Flaneur design © 2017 Dawn Childress. CC BY-NC-SA 4.0.

# build settings
markdown: kramdown
encoding: utf-8

# --STYLES--
accent_color: rgba(18, 127, 157, 1)  # accent color can be any css accepted value
accent_font: Della Respira  # Gogle Fonts import link is in head.html. You can specify the accent font here and it will add it to the main.css

# --SOCIAL--
twitter_username: 
github_username:  

# --MAP SETTINGS--

map-tileset: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
map-credits: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
minZoom: 0
maxZoom: 20
setView: '[48.856614, 2.352222], 12'  # set map center point and zoom. See http://leafletjs.com/reference-1.2.0.html for more info.
marker-grouping: grouped # sets the default clustering action. Options: grouped, single


# Truncates map marker popup on small screens to only display post title
window-height: 600
window-width: 550

# --LINKS--
collections:
  posts:
    output: true
    permalink: /article/:name
  article-index:
    title: Article Index
    output: true
    permalink: /article-index/:name/

permalink: /:categories/:title/

# --MENU--
menu-type: dropdown  # options: dropdown, circle

# settings for circle menu
menu-height: '200px'
menu-width: '200px'
menu-opacity: '.95'

#pages to exclude in menu
exclude_pages: [ "index.html", 'home.md']
